on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build package
        uses: jarias/makepkg-action@v1

      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: '*.xz'
